= firmata-mqtt
A Docker image to publish digital input of a microcontroller over MQTT.

== Description
This project provides a Docker container to read signals from a
microcontroller and publish them over MQTT.

Its main use case is to integrate impulse devices like S0 counters into a home
automation system.

== Prerequisites
* A microcontroller running a http://firmata.org/[Firmata]-compatible firmware
  (e.g. an Arduino running https://github.com/firmata/arduino[Firmata] or 
  https://github.com/firmata/ConfigurableFirmata[ConfigurableFirmata])
* A running MQTT broker (e.g. https://mosquitto.org/[mosquitto])
* Docker
* Optional and recommended: docker-compose

On Debian based systems, dependencies may be installed using the command

 $ sudo apt-get install docker-ce docker-compose


== TL;DR
. Install Docker and MQTT broker.
. Download Arduino IDE and flash Firmata.
. Connect a hardware device (e.g. a S0 counter) to the Arduino:
  * Device signal (+) -> Arduino digital pin (e.g. pin 2)
  * Device GND (-) -> Arduino GND
. Create `docker-compose.yml` configuration file.
. Run `docker-compose-up -d`.

== Usage
. Create a run configuration, e.g.
+
.docker-compose.yml
[source,yaml]
----
  ---
  version: "2.2"
  services:
    firmata-mqtt:
      image: "ckware/firmata-mqtt"
      container_name: "firmata-mqtt"
      init: "true"
      restart: "unless-stopped"
      devices:
      - /dev/ttyUSB0
      environment:
        MQTT_OPTIONS: "-h broker-host"
        FIRMATA_PINS: "9,12"
        FIRMATA_TEMPLATE: "pullup:debounce:falling:1:W"
----
. Start a container:
+
  $ docker-compose up -d

. Receive value changes:
+
  $ mosquitto_sub -h broker-host -v -t firmata/#
  firmata/9/json { "pin":9, "value":1, "timestamp":1592068107.949424, "duration":0.000000, "count":1, "total":1 }
  firmata/12/json { "pin":12, "value":1, "timestamp":1592068107.949565, "duration":0.000000, "count":1, "total":1 }
  firmata/9/json { "pin":9, "value":0, "timestamp":1592068113.127548, "duration":5.178124, "count":1, "total":2, "rate":"695.23 W" }
  firmata/9/json { "pin":9, "value":1, "timestamp":1592068113.298353, "duration":0.170805, "count":2, "total":3 }
  firmata/12/json { "pin":12, "value":0, "timestamp":1592068125.001946, "duration":17.052381, "count":1, "total":2, "rate":"211.11 W" }
  firmata/12/json { "pin":12, "value":1, "timestamp":1592068125.184615, "duration":0.182669, "count":2, "total":3 }
  ^C
  $ docker-compose down
  $ docker-compose logs
  Connecting to Firmata device at /dev/ttyUSB0
  Observed pin(s): 9, 12
  Stopping due to signal TERM
  Disconnected from Firmata device.

== Configuration

.Firmata Options
[cols="1,3,1,1,1"]
|===
|Environment variable|Description|Allowed values|Default|Example

|`FIRMATA_PINS`
|Comma-separated list of pin number with optional pin configuration
|_pin_[_:configuration_][_,pin_[_:configuration_] ...]
|_no default_
|`2`

`2,3,4`

`2,3:input,4:pullup:debounce:falling:1:W`

|`FIRMATA_DEVICE`
|Serial firmata device to read messages from.
|Any special character file
|`/dev/ttyUSB0`
|`/dev/ttyUSB1`

|`FIRMATA_TEMPLATE`
|Template containing the default pin configuration for all pins.
See <<Pin Configuration>> for details.
|`input` / `pullup` `:` `instant` / `debounce` : `none` / `rising` / `falling` / `any` : _number_ : _string_
|`pullup:instant:none`
|`pullup:instant:falling:1:W`

`pullup:debounce:falling:2000:m³/h`

`pullup:debounce`

`:debounce:::W`

|`FIRMATA_INTERVAL`
|Poll interval in milliseconds. When strategy is `instant`, value changes are
reported immediately, not only between poll intervals (see <<Detection strategy>>).
|Positive integer
|`50`
|`100`

|`FIRMATA_COMMAND`
|Command that is run for each message. See <<Command Line Interface>> for details.
|Any executable file
|`/opt/firmata-mqtt/mqtt-publish`
|`/bin/echo`

|`FIRMATA_VERBOSITY`
|Log verbosity.
|`0` / `1` (verbose) / `2` (debug)
|`0`
|`1`
|===

.MQTT Options
[cols="1,3,1,1,1"]
|===
|Environment variable|Description|Allowed values|Default|Example

|`MQTT_OPTIONS`
|MQTT options
|All options supported by https://mosquitto.org/man/mosquitto_pub-1.html[`mosquitto_pub`]
|_none_
|`-v -h broker`

|`MQTT_TOPIC`
|MQTT topic for publishing sensor data
|http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718106[Topic names]
|`firmata`
|`devices/sensors`

|`MQTT_TOPIC_APPEND_ID`
|Append sensor ID to topic?
|`true` / `false`
|`true`
|`true`

|`MQTT_TOPIC_APPEND_FORMAT`
|Append format (one of: `json`, `raw`) to topic?
|`true` / `false`
|`true`
|`true`

|`FORMAT_JSON`
|Publish sensor data in JSON format?
|`true` / `false`
|`true`
|`true`

|`FORMAT_RAW`
|Publish sensor data in raw format?
|`true` / `false`
|`false`
|`false`

|`FORMAT_RAW_SEPARATOR`
|Field separator for raw format
|String
|Whitespace (`\u0020`)
|`,`

|===

=== Pin Configuration
A _pin configuration_ is a colon-separated list of the properties listed in
this section. All properties are optional, trailing colons may be omitted.

==== Pin Mode

Supported pin modes: `input`, `pullup`. Default: `input`.

See https://www.arduino.cc/en/Tutorial/DigitalPins[Digital Pins] in the
Arduino Tutorial for details.

==== Detection strategy

Supported detection strategies: `instant`, `debounce`. Default: `instant`.

* `instant`: Changes will be reported instantly.
* `debounce`: Value changes will be buffered until the current poll interval
  has elapsed (see `FIRMATA_INTERVAL`). This may help when bouncing switches
  are connected to the Firmata device. Please note that this option effectively
  reduces the sample rate to the poll interval, thus the poll interval should be
  chosen carefully according to the connected hardware.

==== Rate trigger

Supported rate triggers: `none`, `falling`, `rising`, `any`. Default: `none`.

When rate trigger ist set, the value changes are supposed to come from a meter
device, and a _rate_ per hour is calculated as
[listing]
3600 / (frequency * duration)

* `falling`: The rate will be calculated for every value change from `1` to `0`.
* `rising`: The rate will be calculated for every value change from `0` to `1`.
* `any`: The rate will be calculated for every value change.
* `none`: The rate will not be calculated.

==== Rate frequency

The frequency tells how many changes per hour the meter device emits.

Supported frequencies: positive numbers

==== Rate unit

The unit contains the unit of the meter device. It is appended to the rate.


== Examples
. Example: S0 energy meters emitting 1000 impulses per kWh
+
[source,yaml]
----
  environment:
    FIRMATA_PINS: "2,3,4"
    FIRMATA_TEMPLATE: "pullup:debounce:falling:1:W"
    MQTT_OPTIONS: "-h broker-host"
----

  - Connect to firmata device at `/dev/ttyUSB0` (default)
  - Configure pins `2`, `3` and `4` as digital input with pullup
  - Enable software debouncing and rate calculation for all pins
  - Publish to `broker-host`

. Example: Different devices with lower sample rate
+
[source,yaml]
----
  environment:
    FIRMATA_DEVICE: "/dev/ttyUSB1"
    FIRMATA_PINS: "2:pullup,3:input"
    FIRMATA_INTERVAL: "20"
    FIRMATA_VERBOSITY: "1"
    MQTT_OPTIONS: "-h broker-host"
----
  - Connect to firmata device at `/dev/ttyUSB1`
  - Disable software debouncing (default)
  - Configure pin `2` as digital input with pullup
  - Configure pin `3` as digital input pin (without pullup)
  - Poll every `20` ms for changes
  - Log verbose messages
  - Publish to `broker-host`

. Example: Debugging
+
[source,yaml]
----
  environment:
    FIRMATA_PINS: "2"
    FIRMATA_VERBOSITY: "2"
    FIRMATA_COMMAND: "/bin/echo"
----
  - Connect to firmata device at `/dev/ttyUSB0`
  - Configure pin `2` as digital input with pullup
  - Log debug messages
  - Do not publish over MQTT but call `/bin/echo` instead.

== Command Line Interface
The main part of this project is a command line program that connects to a
microcontroller using the Firmata protocol and observes its input pins. For
each value change of an observed pin, an external command is called with the
following arguments: 

    pin value timestamp duration count total rate

By default, the external command is a shell script that converts the arguments
to JSON (or optionally keeps them raw) and publishes them over MQTT. The
`command` option may be used to set a different command for custom processing.

=== Arguments

Illustration of a value change:

    ──┐               ┌──  1
      │←───── d ─────→│
      └───────────────┘    0
                      ↑    ↑
                      t    v
    v: value
    t: timestamp
    d: duration


- `pin`: An integer containing the pin number.

- `value`: The value as reported by Firmata, e.g. `0` or `1`.

- `timestamp`: A decimal containing the timestamp of the value change.
  The integer part contains a unix timestamp (seconds since epoch).
  The fractional part has a precision of 9 digits (nanoseconds).

- `duration`: A decimal containing the duration since the previous value change
  with a precision of 9 digits (nanoseconds).

- `count`
  An integer containing ths pin's number of changes to the current value.

- `total`
  An integer containing the pin's total number of changes.

- `rate`
  A string containing the value change rate per hour with an optional unit.

=== Example

    '9' '1' '1591428675.880354881' '2.1215808391571' '3' '5' '1696.85 W'

Explanation: pin **9** has changed to value **1** at **1591428675.880354881**
(2020-06-06 07:31:15 and 880 ms, 385 µs, 881 ns). Before the change, the pin was
stable for about **2.122** seconds (with value 0). This is the **3**rd time
that pin 9 changed to 1. The total number of value changes (either 0 → 1
or 1 → 0) of pin 9 is **5**. If we suppose that an energy meter is connected and
1 Wh has been consumed within the duration, then the duration corresponds to the
power of **1696.85 W**.

== FHEM integration
This section contains an example configuration to integrate a power meter with
https://fhem.de/[FHEM]. The power meter is a S0 counter emitting 1000 impulses
per kWh. It is connected to pin 9 of an Arduino. The pin value stays at `1` when idle and changes to `0` shortly (~70 ms) for every consumed Wh.

.docker-compose.yml
[source,yaml]
----
  ---
  version: "2.2"
  services:
    firmata-mqtt:
      image: "ckware/firmata-mqtt"
      container_name: "firmata-mqtt"
      init: "true"
      restart: "unless-stopped"
      devices:
      - /dev/ttyUSB0
      environment:
        FIRMATA_PINS: "9:pullup:debounce:falling:1:W"
        MQTT_OPTIONS: "-h broker-host"
----

.fhem.cfg
[source,perl]
----
 define mqtt_firmata_pin9 MQTT2_DEVICE
 attr   mqtt_firmata_pin9 devicetopic firmata/9
 # do not use 'pin' and 'value' as readings, and rename 'rate' to 'power'
 attr   mqtt_firmata_pin9 jsonMap pin:0 value:0 rate:power
 attr   mqtt_firmata_pin9 readingList $DEVICETOPIC/json.* { json2nameValue($EVENT, '', $JSONMAP) }
 attr   mqtt_firmata_pin9 stateFormat power W
 attr   mqtt_firmata_pin9 icon icoBlitz
----

== References
* This project is an integration of
  - https://github.com/ntruchsess/perl-firmata[perl-firmata]
  - https://github.com/firmata/protocol[Firmata protocol]
  - https://mosquitto.org/[Mosquitto] - An Open Source MQTT Broker
  - The https://github.com/opencontainers/image-spec[OCI image] format
  - https://www.docker.com/[Docker]

* History and details (in German): https://github.com/git-developer/fhem-examples/wiki/S0-Z%C3%A4hler-mit-ConfigurableFirmata[S0 Zähler mit ConfigurableFirmata]
* Arduino Firmata impementation: https://github.com/firmata/ConfigurableFirmata[ConfigurableFirmata]
* A similar project for temperature sensors: https://github.com/git-developer/tfrec-mqtt[tfrec-mqtt]
